# syntax=docker/dockerfile:1
FROM python:3.11.8 as builder

# https://scrapyd.readthedocs.io/en/stable/install.html
RUN python -m pip install --upgrade pip
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

FROM python:3.11.8-slim as deploy

# https://scrapyd.readthedocs.io/en/stable/config.html
# Alter to docker volumes
# COPY scrapyd.conf /etc/scrapyd/
COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages

EXPOSE 6800
ENTRYPOINT ["scrapyd"]